name: Studies project CI/CD integrated with azdo

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up JDK 17 for selenium tests
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up node for angular project
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install frontend project dependencies
      run: npm ci

    - name: Build Angular app and run Selenium tests
      run: npm run test-selenium

    - name: Uploading the selenium tests error into AZDO
      uses: stefanstranger/azuredevops-bug-action@1.1
      if: failure()
      with:
        OrganizationName: "final-project-mwo"
        PAT: "PAT"
        ProjectName: "mwo-github-azdo-integration"
        AreaPath: "mwo-github-azdo-integration\\Automation"
        IterationPath: "mwo-github-azdo-integration"
        GithubToken: "GithubToken"
        WorkflowFileName: "main.yml"
      env:
        PAT: ${{secrets.PAT}}
        GithubToken: ${{secrets.GITHUBRESTAPISECRET}}
